import { createSlice } from '@reduxjs/toolkit';

const songs = [
  {
    title: "Shape of You",
    singers: ["Ed Sheeran"],
    mood: ["Chill", "Happy", "Romantic"],
    year: 2017,
    album: "Divide",
    duration: "3:53",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg",
    timeStamp: "7:45 PM",
    liked:false

  },
  {
    title: "Blinding Lights",
    singers: ["The Weeknd"],
    mood: ["Energetic", "Night Drive"],
    year: 2019,
    album: "After Hours",
    duration: "3:20",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
    timeStamp: "10:30 PM",
    liked:false
  },
  {
    title: "Tum Hi Ho",
    singers: ["Arijit Singh"],
    mood: ["Sad", "Emotional"],
    year: 2013,
    album: "Aashiqui 2",
    duration: "4:22",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/Umqb9KENgmk/hqdefault.jpg",
    timeStamp: "12:15 AM",
    liked:false
  },
  {
    title: "Kesariya",
    singers: ["Arijit Singh"],
    mood: ["Romantic", "Warm"],
    year: 2022,
    album: "Brahmāstra",
    duration: "4:28",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/BddP6PYo2gs/hqdefault.jpg",
    timeStamp: "6:50 PM",
    liked:true
  },
  {
    title: "Believer",
    singers: ["Imagine Dragons"],
    mood: ["Motivational", "Energetic"],
    year: 2017,
    album: "Evolve",
    duration: "3:24",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/7wtfhZwyrcc/hqdefault.jpg",
    timeStamp: "7:00 AM",
    liked:false
  },
  {
    title: "Despacito",
    singers: ["Luis Fonsi", "Daddy Yankee"],
    mood: ["Party", "Feel Good"],
    year: 2017,
    album: "Vida",
    duration: "3:47",
    language: "Spanish",
    thumbnail: "https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg",
    timeStamp: "9:30 PM",
    liked:false
  },
  {
    title: "Senorita",
    singers: ["Shawn Mendes", "Camila Cabello"],
    mood: ["Romantic", "Chill"],
    year: 2019,
    album: "Single",
    duration: "3:11",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/Pkh8UtuejGw/hqdefault.jpg",
    timeStamp: "8:10 PM",
    liked:false
  },
  {
    title: "Apna Bana Le",
    singers: ["Arijit Singh"],
    mood: ["Soft", "Emotional"],
    year: 2022,
    album: "Bhediya",
    duration: "4:21",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/ElZfdU54Cp8/hqdefault.jpg",
    timeStamp: "11:05 PM",
    liked:true
  },
  {
    title: "Naatu Naatu",
    singers: ["Rahul Sipligunj", "Kaala Bhairava"],
    mood: ["Dance", "Energetic"],
    year: 2022,
    album: "RRR",
    duration: "3:34",
    language: "Telugu",
    thumbnail: "https://c8.alamy.com/comp/2R7R1KD/rrr-naatu-naatu-2022-directed-by-prem-rakshith-2R7R1KD.jpg",
    timeStamp: "5:30 PM",
    liked:false
  },
  {
    title: "Levitating",
    singers: ["Dua Lipa"],
    mood: ["Happy", "Dance"],
    year: 2020,
    album: "Future Nostalgia",
    duration: "3:23",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/TUVcZfQe-Kw/hqdefault.jpg",
    timeStamp: "4:45 PM",
    liked:false
  },
  {
    title: "Perfect",
    singers: ["Ed Sheeran"],
    mood: ["Romantic"],
    year: 2017,
    album: "Divide",
    duration: "4:23",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/2Vv-BfVoq4g/hqdefault.jpg",
    timeStamp: "9:00 PM",
    liked:true
  },
  {
    title: "Heat Waves",
    singers: ["Glass Animals"],
    mood: ["Chill"],
    year: 2020,
    album: "Dreamland",
    duration: "3:58",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/mRD0-GxqHVo/hqdefault.jpg",
    timeStamp: "11:20 PM",
    liked:false
  },
  {
    title: "On My Way",
    singers: ["Alan Walker"],
    mood: ["Motivational"],
    year: 2019,
    album: "Single",
    duration: "3:14",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/dhYOPzcsbGM/hqdefault.jpg",
    timeStamp: "6:30 AM",
    liked:false
  },
  {
    title: "Closer",
    singers: ["The Chainsmokers", "Halsey"],
    mood: ["Chill", "Romantic"],
    year: 2016,
    album: "Single",
    duration: "4:05",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/PT2_F-1esPk/hqdefault.jpg",
    timeStamp: "8:25 PM",
    liked:false
  },
  {
    title: "Hawayein",
    singers: ["Arijit Singh"],
    mood: ["Romantic"],
    year: 2017,
    album: "Jab Harry Met Sejal",
    duration: "4:50",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/cYOB941gyXI/hqdefault.jpg",
    timeStamp: "7:10 PM",
    liked:false
  },
  {
    title: "Attention",
    singers: ["Charlie Puth"],
    mood: ["Chill"],
    year: 2017,
    album: "Voicenotes",
    duration: "3:31",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/nfs8NYg7yQM/hqdefault.jpg",
    timeStamp: "6:15 PM",
    liked:true
  },
  {
    title: "Love Me Like You Do",
    singers: ["Ellie Goulding"],
    mood: ["Romantic"],
    year: 2015,
    album: "Delirium",
    duration: "4:12",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/AJtDXIazrMo/hqdefault.jpg",
    timeStamp: "9:40 PM",
    liked:false
  },
  {
    title: "Faded",
    singers: ["Alan Walker"],
    mood: ["Sad", "Chill"],
    year: 2015,
    album: "Different World",
    duration: "3:32",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg",
    timeStamp: "12:40 AM",
    liked:false
  },
  {
    title: "Ghungroo",
    singers: ["Arijit Singh", "Shilpa Rao"],
    mood: ["Dance", "Happy"],
    year: 2019,
    album: "War",
    duration: "5:02",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/qFkNATtc3mc/hqdefault.jpg",
    timeStamp: "5:50 PM",
    liked:false
  },
  {
    title: "Stay",
    singers: ["The Kid LAROI", "Justin Bieber"],
    mood: ["Energetic"],
    year: 2021,
    album: "Single",
    duration: "2:21",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/kTJczUoc26U/hqdefault.jpg",
    timeStamp: "3:30 PM",
    liked:true
  },
  {
    title: "Let Me Love You",
    singers: ["DJ Snake", "Justin Bieber"],
    mood: ["Party"],
    year: 2016,
    album: "Encore",
    duration: "3:25",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/SMs0GnYze34/hqdefault.jpg",
    timeStamp: "10:00 PM",
    liked:false
  },
  {
    title: "Channa Mereya",
    singers: ["Arijit Singh"],
    mood: ["Sad"],
    year: 2016,
    album: "Ae Dil Hai Mushkil",
    duration: "4:49",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/284Ov7ysmfA/hqdefault.jpg",
    timeStamp: "1:10 AM",
    liked:false
  },
  {
    title: "Tera Ban Jaunga",
    singers: ["Akhil Sachdeva"],
    mood: ["Romantic"],
    year: 2019,
    album: "Kabir Singh",
    duration: "3:56",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/Qdz5n1Xe5Qo/hqdefault.jpg",
    timeStamp: "8:00 PM",
    liked:false
  },
  {
    title: "Peaches",
    singers: ["Justin Bieber"],
    mood: ["Chill"],
    year: 2021,
    album: "Justice",
    duration: "3:18",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/tQ0yjYUFKAE/hqdefault.jpg",
    timeStamp: "2:15 PM",
    liked:true
  },
  {
    title: "Industry Baby",
    singers: ["Lil Nas X"],
    mood: ["Hype"],
    year: 2021,
    album: "Montero",
    duration: "3:32",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/UTHLKHL_whs/hqdefault.jpg",
    timeStamp: "4:10 PM",
    liked:false
  },
  {
    title: "Raataan Lambiyan",
    singers: ["Jubin Nautiyal"],
    mood: ["Romantic"],
    year: 2021,
    album: "Shershaah",
    duration: "3:50",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/gvyUuxdRdR4/hqdefault.jpg",
    timeStamp: "7:20 PM",
    liked:false
  },
  {
    title: "Lovely",
    singers: ["Billie Eilish"],
    mood: ["Sad", "Emotional"],
    year: 2018,
    album: "Single",
    duration: "3:21",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/V1Pl8CzNzCw/hqdefault.jpg",
    timeStamp: "12:55 AM",
    liked:false
  },
  {
    title: "Bones",
    singers: ["Imagine Dragons"],
    mood: ["Energetic"],
    year: 2022,
    album: "Mercury",
    duration: "2:45",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/TO-_3tck2tg/hqdefault.jpg",
    timeStamp: "3:50 PM",
    liked:false
  },
  {
    title: "Calm Down",
    singers: ["Rema"],
    mood: ["Chill", "Feel Good"],
    year: 2022,
    album: "Rave & Roses",
    duration: "3:39",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/WcIcVapfqXw/hqdefault.jpg",
    timeStamp: "6:05 PM",
    liked:true
  },
  {
    title: "Perfect Strangers",
    singers: ["Jonas Blue"],
    mood: ["Party"],
    year: 2016,
    album: "Blue",
    duration: "3:16",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/EkHTsc9PU2A/hqdefault.jpg",
    timeStamp: "9:50 PM",
    liked:false
  }
  ,
  {
  title: "Perfect",
  singers: ["Ed Sheeran"],
  mood: ["Romantic", "Soft", "Emotional"],
  year: 2017,
  album: "Divide",
  duration: "4:23",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/2Vv-BfVoq4g/hqdefault.jpg",
  timeStamp: "8:30 PM",
    liked:false
},
{
  title: "Faded",
  singers: ["Alan Walker"],
  mood: ["Sad", "Emotional", "Chill"],
  year: 2015,
  album: "Different World",
  duration: "3:32",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg",
  timeStamp: "12:20 AM",
    liked:false
},
{
  title: "On My Way",
  singers: ["Alan Walker", "Sabrina Carpenter"],
  mood: ["Motivational", "Energetic", "Travel"],
  year: 2019,
  album: "Single",
  duration: "3:13",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/dhYOPzcsbGM/hqdefault.jpg",
  timeStamp: "6:45 AM",
  liked:false
},
{
  title: "Raataan Lambiyan",
  singers: ["Jubin Nautiyal", "Asees Kaur"],
  mood: ["Romantic", "Calm", "Soft"],
  year: 2021,
  album: "Shershaah",
  duration: "3:50",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/gvyUuxdRdR4/hqdefault.jpg",
  timeStamp: "7:35 PM",
    liked:true
},
{
  title: "Ranjha",
  singers: ["B Praak", "Jasleen Royal"],
  mood: ["Emotional", "Sad", "Romantic"],
  year: 2021,
  album: "Shershaah",
  duration: "3:48",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/VuG7ge_8I2Y/hqdefault.jpg",
  timeStamp: "11:30 PM",
    liked:false
},
{
  title: "We Rollin",
  singers: ["Shubh"],
  mood: ["Hype", "Cool", "Chill"],
  year: 2021,
  album: "Single",
  duration: "3:19",
  language: "Punjabi",
  thumbnail: "https://i.ytimg.com/vi/Ml9uJNF_kXk/hqdefault.jpg",
  timeStamp: "3:40 PM",
    liked:false
},
{
  title: "295",
  singers: ["Sidhu Moose Wala"],
  mood: ["Serious", "Real Talk", "Emotional"],
  year: 2021,
  album: "Moosetape",
  duration: "4:10",
  language: "Punjabi",
  thumbnail: "https://i.ytimg.com/vi/n_FCrCQ6-bA/hqdefault.jpg",
  timeStamp: "4:20 PM",
    liked:false
},
{
  title: "Tera Ban Jaunga",
  singers: ["Akhil Sachdeva", "Tulsi Kumar"],
  mood: ["Romantic", "Soft", "Emotional"],
  year: 2019,
  album: "Kabir Singh",
  duration: "3:56",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/Qdz5n1Xe5Qo/hqdefault.jpg",
  timeStamp: "8:15 PM",
    liked:false
},
{
  title: "Attention",
  singers: ["Charlie Puth"],
  mood: ["Chill", "Groovy", "Attitude"],
  year: 2017,
  album: "Voicenotes",
  duration: "3:31",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/nfs8NYg7yQM/hqdefault.jpg",
  timeStamp: "6:25 PM",
    liked:false
},
{
  title: "See You Again",
  singers: ["Wiz Khalifa", "Charlie Puth"],
  mood: ["Emotional", "Sad", "Memories"],
  year: 2015,
  album: "Furious 7",
  duration: "3:57",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/RgKAFK5djSk/hqdefault.jpg",
  timeStamp: "1:45 AM",
    liked:true
},
{
  title: "Gangnam Style",
  singers: ["PSY"],
  mood: ["Fun", "Dance", "Party"],
  year: 2012,
  album: "PSY 6",
  duration: "3:39",
  language: "Korean",
  thumbnail: "https://i.ytimg.com/vi/9bZkp7q19f0/hqdefault.jpg",
  timeStamp: "5:20 PM",
    liked:false
},
{
  title: "How You Like That",
  singers: ["BLACKPINK"],
  mood: ["Hype", "Powerful", "Energetic"],
  year: 2020,
  album: "The Album",
  duration: "3:01",
  language: "Korean",
  thumbnail: "https://i.ytimg.com/vi/ioNng23DkIM/hqdefault.jpg",
  timeStamp: "5:35 PM",
    liked:false
},
{
  title: "Cheap Thrills",
  singers: ["Sia"],
  mood: ["Party", "Dance", "Fun"],
  year: 2016,
  album: "This Is Acting",
  duration: "3:31",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/31crA53Dgu0/hqdefault.jpg",
  timeStamp: "9:10 PM",
    liked:false
},
{
  title: "Kar Gayi Chull",
  singers: ["Badshah", "Neha Kakkar"],
  mood: ["Party", "Dance", "Hype"],
  year: 2016,
  album: "Kapoor & Sons",
  duration: "3:07",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/NTHz9ephYTw/hqdefault.jpg",
  timeStamp: "9:20 PM",
    liked:true
},
{
  title: "Abhi Toh Party Shuru Hui Hai",
  singers: ["Badshah", "Aastha Gill"],
  mood: ["Party", "Hype", "Dance"],
  year: 2014,
  album: "Khoobsurat",
  duration: "2:59",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/8LZgzAZ2lpQ/hqdefault.jpg",
  timeStamp: "9:25 PM",
    liked:false
},
{
  title: "Nashe Si Chadh Gayi",
  singers: ["Arijit Singh"],
  mood: ["Party", "Dance", "Romantic"],
  year: 2016,
  album: "Befikre",
  duration: "3:57",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/Wd2B8OAotU8/hqdefault.jpg",
  timeStamp: "9:35 PM",
    liked:false
},
{
  title: "London Thumakda",
  singers: ["Neha Kakkar", "Sonu Kakkar"],
  mood: ["Wedding", "Dance", "Fun"],
  year: 2014,
  album: "Queen",
  duration: "3:50",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/udra3Mfw2oo/hqdefault.jpg",
  timeStamp: "9:45 PM",
    liked:false
},
{
  title: "Morni Banke",
  singers: ["Guru Randhawa", "Neha Kakkar"],
  mood: ["Dance", "Party", "Wedding"],
  year: 2018,
  album: "Badhaai Ho",
  duration: "3:18",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/1EadhOBcfI0/hqdefault.jpg",
  timeStamp: "9:55 PM",
    liked:false
},
{
  title: "Proper Patola",
  singers: ["Diljit Dosanjh", "Badshah"],
  mood: ["Party", "Cool", "Dance"],
  year: 2018,
  album: "Namaste England",
  duration: "3:05",
  language: "Punjabi",
  thumbnail: "https://i.ytimg.com/vi/YmXJp4RtBCM/hqdefault.jpg",
  timeStamp: "10:05 PM",
    liked:false
},
{
  title: "High Heels",
  singers: ["Yo Yo Honey Singh", "Jaz Dhami"],
  mood: ["Party", "Dance", "Hype"],
  year: 2016,
  album: "Ki & Ka",
  duration: "3:24",
  language: "Punjabi",
  thumbnail: "https://i.ytimg.com/vi/N_KpjLhJa1k/hqdefault.jpg",
  timeStamp: "10:15 PM",
    liked:true
},
{
  title: "Bom Diggy Diggy",
  singers: ["Zack Knight", "Jasmin Walia"],
  mood: ["Party", "Dance", "Fun"],
  year: 2018,
  album: "Sonu Ke Titu Ki Sweety",
  duration: "3:58",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/yIIGQB6EMAM/hqdefault.jpg",
  timeStamp: "10:25 PM",
    liked:false
},
{
  title: "Aankh Marey",
  singers: ["Neha Kakkar", "Mika Singh"],
  mood: ["Party", "Dance", "Hype"],
  year: 2018,
  album: "Simmba",
  duration: "3:32",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/_KhQT-LGb-4/hqdefault.jpg",
  timeStamp: "10:35 PM",
    liked:false
},
{
  title: "Dil Chori",
  singers: ["Yo Yo Honey Singh", "Simar Kaur"],
  mood: ["Party", "Dance", "Wedding"],
  year: 2018,
  album: "Sonu Ke Titu Ki Sweety",
  duration: "3:46",
  language: "Punjabi",
  thumbnail: "https://i.ytimg.com/vi/ZmDBbnmKpqQ/hqdefault.jpg",
  timeStamp: "10:45 PM",
    liked:false
}
  ,
  {
    title: "Night Changes",
    singers: ["One Direction"],
    mood: ["Night Drive", "Chill"],
    year: 2014,
    album: "Four",
    duration: "3:46",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/syFZfO_wfMQ/hqdefault.jpg",
    timeStamp: "11:45 PM",
    liked:true
  },
  {
    title: "Drive",
    singers: ["Oh Wonder"],
    mood: ["Night Drive", "Chill"],
    year: 2017,
    album: "Ultralife",
    duration: "3:20",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/_w5jPT8LMF0/hqdefault.jpg",
    timeStamp: "12:10 AM",
    liked:false
  },
  {
    title: "Sunflower",
    singers: ["Post Malone"],
    mood: ["Feel Good", "Chill"],
    year: 2018,
    album: "Spider-Man OST",
    duration: "2:38",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/ApXoWvfEYVU/hqdefault.jpg",
    timeStamp: "4:00 PM",
    liked:false
  },
  {
    title: "Good Life",
    singers: ["OneRepublic"],
    mood: ["Feel Good", "Happy"],
    year: 2011,
    album: "Waking Up",
    duration: "4:13",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/jZhQOvvV45w/hqdefault.jpg",
    timeStamp: "5:10 PM",
    liked:false
  },
  {
    title: "Till I Collapse",
    singers: ["Eminem"],
    mood: ["Workout", "Motivational"],
    year: 2002,
    album: "The Eminem Show",
    duration: "4:57",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/Obim8BYGnOE/hqdefault.jpg",
    timeStamp: "6:00 AM",
    liked:false
  },
  {
    title: "Stronger",
    singers: ["Kanye West"],
    mood: ["Workout", "Energetic"],
    year: 2007,
    album: "Graduation",
    duration: "5:12",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/PsO6ZnUZI0g/hqdefault.jpg",
    timeStamp: "6:30 AM",
    liked:true
  },
  {
    title: "Believer (Remix)",
    singers: ["Imagine Dragons"],
    mood: ["Workout", "Motivational"],
    year: 2018,
    album: "Single",
    duration: "3:30",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/7wtfhZwyrcc/hqdefault.jpg",
    timeStamp: "7:00 AM",
    liked:false
  },
  {
    title: "Let Her Go",
    singers: ["Passenger"],
    mood: ["Sad", "Emotional"],
    year: 2012,
    album: "All the Little Lights",
    duration: "4:12",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/RBumgq5yVrA/hqdefault.jpg",
    timeStamp: "1:30 AM",
    liked:false
  },
  {
    title: "Someone Like You",
    singers: ["Adele"],
    mood: ["Sad", "Emotional"],
    year: 2011,
    album: "21",
    duration: "4:45",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/hLQl3WQQoQ0/hqdefault.jpg",
    timeStamp: "2:00 AM",
    liked:false
  },
  {
    title: "Kesariya (Lo-fi)",
    singers: ["Arijit Singh"],
    mood: ["Warm", "Chill"],
    year: 2022,
    album: "Brahmāstra",
    duration: "3:00",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/BddP6PYo2gs/hqdefault.jpg",
    timeStamp: "7:30 PM",
    liked:false
  },
  {
    title: "Shayad",
    singers: ["Arijit Singh"],
    mood: ["Warm", "Romantic"],
    year: 2020,
    album: "Love Aaj Kal",
    duration: "4:07",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/MJyKN-8UncM/hqdefault.jpg",
    timeStamp: "8:20 PM",
    liked:false
  },
  {
    title: "Hall of Fame",
    singers: ["The Script"],
    mood: ["Motivational", "Focus"],
    year: 2012,
    album: "Single",
    duration: "3:22",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/mk48xRzuNvA/hqdefault.jpg",
    timeStamp: "9:00 AM",
    liked:true
  },
  {
    title: "Counting Stars",
    singers: ["OneRepublic"],
    mood: ["Focus", "Feel Good"],
    year: 2013,
    album: "Native",
    duration: "4:17",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/hT_nvWreIhg/hqdefault.jpg",
    timeStamp: "3:00 PM",
    liked:false
  },
  {
    title: "Perfect Strangers (Acoustic)",
    singers: ["Jonas Blue"],
    mood: ["Chill", "Focus"],
    year: 2016,
    album: "Blue",
    duration: "3:30",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/EkHTsc9PU2A/hqdefault.jpg",
    timeStamp: "5:40 PM",
    liked:false
  }


  ,
  {
  title: "Until I Found You",
  singers: ["Stephen Sanchez"],
  mood: ["Romantic", "Warm"],
  year: 2021,
  album: "Easy On My Eyes",
  duration: "2:57",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/GxldQ9eX2wo/hqdefault.jpg",
  timeStamp: "8:40 PM",
    liked:false
},

{
  title: "Night Changes",
  singers: ["One Direction"],
  mood: ["Night drive", "Chill"],
  year: 2014,
  album: "Four",
  duration: "3:46",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/syFZfO_wfMQ/hqdefault.jpg",
  timeStamp: "11:50 PM",
    liked:true
},
{
  title: "The Night We Met",
  singers: ["Lord Huron"],
  mood: ["Night drive", "Sad"],
  year: 2015,
  album: "Strange Trails",
  duration: "3:28",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/KtlgYxa6BMU/hqdefault.jpg",
  timeStamp: "12:30 AM",
    liked:false
},

{
  title: "Uptown Funk",
  singers: ["Bruno Mars"],
  mood: ["Party", "Dance"],
  year: 2014,
  album: "Uptown Special",
  duration: "4:30",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg",
  timeStamp: "5:00 PM",
    liked:false
},
{
  title: "Kala Chashma",
  singers: ["Badshah", "Neha Kakkar"],
  mood: ["Party", "Dance"],
  year: 2016,
  album: "Baar Baar Dekho",
  duration: "3:07",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/k4yXQkG2s1E/hqdefault.jpg",
  timeStamp: "9:15 PM",
    liked:false
},

{
  title: "Let Me Down Slowly",
  singers: ["Alec Benjamin"],
  mood: ["Sad"],
  year: 2018,
  album: "Narrated for You",
  duration: "2:49",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/50VNCymT-Cs/hqdefault.jpg",
  timeStamp: "1:55 AM",
    liked:false
},
{
  title: "Agar Tum Saath Ho",
  singers: ["Alka Yagnik", "Arijit Singh"],
  mood: ["Sad", "Warm"],
  year: 2015,
  album: "Tamasha",
  duration: "5:41",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/sK7riqg2mr4/hqdefault.jpg",
  timeStamp: "2:10 AM",
    liked:false
},

{
  title: "Eye of the Tiger",
  singers: ["Survivor"],
  mood: ["Workout", "Motivational"],
  year: 1982,
  album: "Eye of the Tiger",
  duration: "4:05",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/btPJPFnesV4/hqdefault.jpg",
  timeStamp: "6:15 AM",
    liked:true
},

{
  title: "Good Time",
  singers: ["Owl City", "Carly Rae Jepsen"],
  mood: ["Feel good", "Flow"],
  year: 2012,
  album: "The Midsummer Station",
  duration: "3:26",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/H7HmzwI67ec/hqdefault.jpg",
  timeStamp: "4:20 PM",
    liked:false
},
{
  title: "Ilahi",
  singers: ["Arijit Singh"],
  mood: ["Flow", "Feel good"],
  year: 2013,
  album: "YJHD",
  duration: "3:32",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/fdubeMFwuGs/hqdefault.jpg",
  timeStamp: "4:35 PM",
    liked:false
},

{
  title: "Experience",
  singers: ["Ludovico Einaudi"],
  mood: ["Focus"],
  year: 2013,
  album: "In a Time Lapse",
  duration: "5:15",
  language: "Instrumental",
  thumbnail: "https://i.ytimg.com/vi/hN_q-_nGv4U/hqdefault.jpg",
  timeStamp: "9:30 AM",
    liked:false
},
{
  title: "Weightless",
  singers: ["Marconi Union"],
  mood: ["Focus", "Chill"],
  year: 2011,
  album: "Weightless",
  duration: "8:00",
  language: "Instrumental",
  thumbnail: "https://i.ytimg.com/vi/UfcAVejslrU/hqdefault.jpg",
  timeStamp: "10:00 AM",
    liked:false
},

// 🔥 Mix (Chill + Romantic + Flow)
{
  title: "Perfect Duet",
  singers: ["Ed Sheeran", "Beyonce"],
  mood: ["Romantic", "Chill"],
  year: 2017,
  album: "Divide",
  duration: "4:19",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/817P8W8-mGE/hqdefault.jpg",
  timeStamp: "8:50 PM",
    liked:false
},
{
  title: "Kaise Hua",
  singers: ["Vishal Mishra"],
  mood: ["Romantic", "Chill"],
  year: 2019,
  album: "Kabir Singh",
  duration: "3:54",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/WWXm39leYew/hqdefault.jpg",
  timeStamp: "8:05 PM",
    liked:false
},

// 🕺 Dance / Party / Hype
{
  title: "Titanium",
  singers: ["David Guetta", "Sia"],
  mood: ["Dance", "Motivational"],
  year: 2011,
  album: "Nothing but the Beat",
  duration: "4:05",
  language: "English",
  thumbnail: "https://i.ytimg.com/vi/JRfuAukYTKg/hqdefault.jpg",
  timeStamp: "6:10 PM",
    liked:false
},
{
  title: "Malang",
  singers: ["Ved Sharma"],
  mood: ["Dance", "Feel good"],
  year: 2020,
  album: "Malang",
  duration: "4:37",
  language: "Hindi",
  thumbnail: "https://i.ytimg.com/vi/KBIq11mNB0I/hqdefault.jpg",
  timeStamp: "6:20 PM",
    liked:false
}
];

const songPoolSlice = createSlice({
    name : "songPool",
    initialState : {value : songs},
    reducers : {
        toggleLike: (state, action) => {
          const index = state.value.findIndex(s => s.title === action.payload.title);
          if (index !== -1) {
              state.value[index].liked = !state.value[index].liked;
          }},
        addSong : (state,action) => {
          state.value = [...state.value,action.payload];
          }
      }
});

export const {toggleLike,addSong} = songPoolSlice.actions;
export default songPoolSlice.reducer;