import { createSlice } from '@reduxjs/toolkit';

const songs = [
  // ───── ENGLISH – Romantic / Chill ─────
  {
    title: "Shape of You",
    singers: ["Ed Sheeran"],
    mood: ["Chill", "Happy", "Romantic"],
    year: 2017,
    album: "Divide",
    duration: "3:53",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg",
    timeStamp: "7:45 PM",
    liked: false
  },
  {
    title: "Perfect",
    singers: ["Ed Sheeran"],
    mood: ["Romantic", "Soft", "Emotional"],
    year: 2017,
    album: "Divide",
    duration: "4:23",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/2Vv-BfVoq4g/hqdefault.jpg",
    timeStamp: "9:00 PM",
    liked: true
  },
  {
    title: "Perfect Duet",
    singers: ["Ed Sheeran", "Beyonce"],
    mood: ["Romantic", "Chill"],
    year: 2017,
    album: "Divide",
    duration: "4:19",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/817P8W8-mGE/hqdefault.jpg",
    timeStamp: "8:50 PM",
    liked: false
  },
  {
    title: "Senorita",
    singers: ["Shawn Mendes", "Camila Cabello"],
    mood: ["Romantic", "Chill"],
    year: 2019,
    album: "Single",
    duration: "3:11",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/Pkh8UtuejGw/hqdefault.jpg",
    timeStamp: "8:10 PM",
    liked: false
  },
  {
    title: "Closer",
    singers: ["The Chainsmokers", "Halsey"],
    mood: ["Chill", "Romantic"],
    year: 2016,
    album: "Single",
    duration: "4:05",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/PT2_F-1esPk/hqdefault.jpg",
    timeStamp: "8:25 PM",
    liked: false
  },
  {
    title: "Love Me Like You Do",
    singers: ["Ellie Goulding"],
    mood: ["Romantic"],
    year: 2015,
    album: "Delirium",
    duration: "4:12",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/AJtDXIazrMo/hqdefault.jpg",
    timeStamp: "9:40 PM",
    liked: false
  },
  {
    title: "Until I Found You",
    singers: ["Stephen Sanchez"],
    mood: ["Romantic", "Warm"],
    year: 2021,
    album: "Easy On My Eyes",
    duration: "2:57",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/GxldQ9eX2wo/hqdefault.jpg",
    timeStamp: "8:40 PM",
    liked: false
  },
  {
    title: "All of Me",
    singers: ["John Legend"],
    mood: ["Romantic", "Emotional"],
    year: 2013,
    album: "Love in the Future",
    duration: "4:30",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/450p7goxZqg/hqdefault.jpg",
    timeStamp: "9:15 PM",
    liked: false
  },
  {
    title: "Thinking Out Loud",
    singers: ["Ed Sheeran"],
    mood: ["Romantic", "Warm"],
    year: 2014,
    album: "X",
    duration: "4:41",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/lp-EO5I60KA/hqdefault.jpg",
    timeStamp: "8:55 PM",
    liked: true
  },
  {
    title: "A Thousand Years",
    singers: ["Christina Perri"],
    mood: ["Romantic", "Emotional"],
    year: 2011,
    album: "lovestrong.",
    duration: "4:45",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/rtOvBOTyX00/hqdefault.jpg",
    timeStamp: "9:30 PM",
    liked: false
  },

  // ───── ENGLISH – Chill / Feel Good ─────
  {
    title: "Heat Waves",
    singers: ["Glass Animals"],
    mood: ["Chill"],
    year: 2020,
    album: "Dreamland",
    duration: "3:58",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/mRD0-GxqHVo/hqdefault.jpg",
    timeStamp: "11:20 PM",
    liked: false
  },
  {
    title: "Attention",
    singers: ["Charlie Puth"],
    mood: ["Chill", "Groovy", "Attitude"],
    year: 2017,
    album: "Voicenotes",
    duration: "3:31",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/nfs8NYg7yQM/hqdefault.jpg",
    timeStamp: "6:15 PM",
    liked: true
  },
  {
    title: "Peaches",
    singers: ["Justin Bieber"],
    mood: ["Chill"],
    year: 2021,
    album: "Justice",
    duration: "3:18",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/tQ0yjYUFKAE/hqdefault.jpg",
    timeStamp: "2:15 PM",
    liked: true
  },
  {
    title: "Sunflower",
    singers: ["Post Malone"],
    mood: ["Feel Good", "Chill"],
    year: 2018,
    album: "Spider-Man OST",
    duration: "2:38",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/ApXoWvfEYVU/hqdefault.jpg",
    timeStamp: "4:00 PM",
    liked: false
  },
  {
    title: "Good Life",
    singers: ["OneRepublic"],
    mood: ["Feel Good", "Happy"],
    year: 2011,
    album: "Waking Up",
    duration: "4:13",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/jZhQOvvV45w/hqdefault.jpg",
    timeStamp: "5:10 PM",
    liked: false
  },
  {
    title: "Calm Down",
    singers: ["Rema"],
    mood: ["Chill", "Feel Good"],
    year: 2022,
    album: "Rave & Roses",
    duration: "3:39",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/WcIcVapfqXw/hqdefault.jpg",
    timeStamp: "6:05 PM",
    liked: true
  },
  {
    title: "Good Time",
    singers: ["Owl City", "Carly Rae Jepsen"],
    mood: ["Feel Good", "Flow"],
    year: 2012,
    album: "The Midsummer Station",
    duration: "3:26",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/H7HmzwI67ec/hqdefault.jpg",
    timeStamp: "4:20 PM",
    liked: false
  },
  {
    title: "Counting Stars",
    singers: ["OneRepublic"],
    mood: ["Focus", "Feel Good"],
    year: 2013,
    album: "Native",
    duration: "4:17",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/hT_nvWreIhg/hqdefault.jpg",
    timeStamp: "3:00 PM",
    liked: false
  },
  {
    title: "Watermelon Sugar",
    singers: ["Harry Styles"],
    mood: ["Feel Good", "Happy"],
    year: 2019,
    album: "Fine Line",
    duration: "2:54",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/E07s5ZYygMg/hqdefault.jpg",
    timeStamp: "3:30 PM",
    liked: false
  },
  {
    title: "As It Was",
    singers: ["Harry Styles"],
    mood: ["Chill", "Feel Good"],
    year: 2022,
    album: "Harry's House",
    duration: "2:37",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/H5v3kku4y6Q/hqdefault.jpg",
    timeStamp: "4:50 PM",
    liked: false
  },
  {
    title: "Somewhere Only We Know",
    singers: ["Keane"],
    mood: ["Warm", "Emotional"],
    year: 2004,
    album: "Hopes and Fears",
    duration: "3:57",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/Oalbertdco1Y/hqdefault.jpg",
    timeStamp: "5:25 PM",
    liked: false
  },

  // ───── ENGLISH – Night Drive ─────
  {
    title: "Night Changes",
    singers: ["One Direction"],
    mood: ["Night Drive", "Chill"],
    year: 2014,
    album: "Four",
    duration: "3:46",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/syFZfO_wfMQ/hqdefault.jpg",
    timeStamp: "11:45 PM",
    liked: true
  },
  {
    title: "Drive",
    singers: ["Oh Wonder"],
    mood: ["Night Drive", "Chill"],
    year: 2017,
    album: "Ultralife",
    duration: "3:20",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/_w5jPT8LMF0/hqdefault.jpg",
    timeStamp: "12:10 AM",
    liked: false
  },
  {
    title: "The Night We Met",
    singers: ["Lord Huron"],
    mood: ["Night Drive", "Sad"],
    year: 2015,
    album: "Strange Trails",
    duration: "3:28",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/KtlgYxa6BMU/hqdefault.jpg",
    timeStamp: "12:30 AM",
    liked: false
  },
  {
    title: "Blinding Lights",
    singers: ["The Weeknd"],
    mood: ["Energetic", "Night Drive"],
    year: 2019,
    album: "After Hours",
    duration: "3:20",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/4NRXx6U8ABQ/hqdefault.jpg",
    timeStamp: "10:30 PM",
    liked: false
  },
  {
    title: "Starboy",
    singers: ["The Weeknd"],
    mood: ["Night Drive", "Hype"],
    year: 2016,
    album: "Starboy",
    duration: "3:50",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/34Na4j8AVgA/hqdefault.jpg",
    timeStamp: "11:00 PM",
    liked: false
  },
  {
    title: "Midnight Rain",
    singers: ["Taylor Swift"],
    mood: ["Night Drive", "Emotional"],
    year: 2022,
    album: "Midnights",
    duration: "3:42",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/MhWNdtHX7Pw/hqdefault.jpg",
    timeStamp: "12:45 AM",
    liked: false
  },

  // ───── ENGLISH – Sad / Emotional ─────
  {
    title: "Faded",
    singers: ["Alan Walker"],
    mood: ["Sad", "Emotional", "Chill"],
    year: 2015,
    album: "Different World",
    duration: "3:32",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/60ItHLz5WEA/hqdefault.jpg",
    timeStamp: "12:20 AM",
    liked: false
  },
  {
    title: "Let Her Go",
    singers: ["Passenger"],
    mood: ["Sad", "Emotional"],
    year: 2012,
    album: "All the Little Lights",
    duration: "4:12",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/RBumgq5yVrA/hqdefault.jpg",
    timeStamp: "1:30 AM",
    liked: false
  },
  {
    title: "Someone Like You",
    singers: ["Adele"],
    mood: ["Sad", "Emotional"],
    year: 2011,
    album: "21",
    duration: "4:45",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/hLQl3WQQoQ0/hqdefault.jpg",
    timeStamp: "2:00 AM",
    liked: false
  },
  {
    title: "Lovely",
    singers: ["Billie Eilish"],
    mood: ["Sad", "Emotional"],
    year: 2018,
    album: "Single",
    duration: "3:21",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/V1Pl8CzNzCw/hqdefault.jpg",
    timeStamp: "12:55 AM",
    liked: false
  },
  {
    title: "See You Again",
    singers: ["Wiz Khalifa", "Charlie Puth"],
    mood: ["Emotional", "Sad", "Memories"],
    year: 2015,
    album: "Furious 7",
    duration: "3:57",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/RgKAFK5djSk/hqdefault.jpg",
    timeStamp: "1:45 AM",
    liked: true
  },
  {
    title: "Let Me Down Slowly",
    singers: ["Alec Benjamin"],
    mood: ["Sad"],
    year: 2018,
    album: "Narrated for You",
    duration: "2:49",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/50VNCymT-Cs/hqdefault.jpg",
    timeStamp: "1:55 AM",
    liked: false
  },
  {
    title: "Fix You",
    singers: ["Coldplay"],
    mood: ["Sad", "Emotional"],
    year: 2005,
    album: "X&Y",
    duration: "4:55",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/k4V3Mo61fJM/hqdefault.jpg",
    timeStamp: "2:20 AM",
    liked: false
  },
  {
    title: "Skinny Love",
    singers: ["Bon Iver"],
    mood: ["Sad", "Emotional"],
    year: 2008,
    album: "For Emma, Forever Ago",
    duration: "3:58",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/ssdgFoZstZ0/hqdefault.jpg",
    timeStamp: "2:40 AM",
    liked: false
  },
  {
    title: "Happier",
    singers: ["Olivia Rodrigo"],
    mood: ["Sad", "Emotional"],
    year: 2021,
    album: "SOUR",
    duration: "3:37",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/PV1S7m-IzqQ/hqdefault.jpg",
    timeStamp: "1:10 AM",
    liked: false
  },

  // ───── ENGLISH – Energetic / Motivational / Workout ─────
  {
    title: "Believer",
    singers: ["Imagine Dragons"],
    mood: ["Motivational", "Energetic"],
    year: 2017,
    album: "Evolve",
    duration: "3:24",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/7wtfhZwyrcc/hqdefault.jpg",
    timeStamp: "7:00 AM",
    liked: false
  },
  {
    title: "Bones",
    singers: ["Imagine Dragons"],
    mood: ["Energetic"],
    year: 2022,
    album: "Mercury",
    duration: "2:45",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/TO-_3tck2tg/hqdefault.jpg",
    timeStamp: "3:50 PM",
    liked: false
  },
  {
    title: "On My Way",
    singers: ["Alan Walker", "Sabrina Carpenter"],
    mood: ["Motivational", "Energetic", "Travel"],
    year: 2019,
    album: "Single",
    duration: "3:13",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/dhYOPzcsbGM/hqdefault.jpg",
    timeStamp: "6:45 AM",
    liked: false
  },
  {
    title: "Till I Collapse",
    singers: ["Eminem"],
    mood: ["Workout", "Motivational"],
    year: 2002,
    album: "The Eminem Show",
    duration: "4:57",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/Obim8BYGnOE/hqdefault.jpg",
    timeStamp: "6:00 AM",
    liked: false
  },
  {
    title: "Stronger",
    singers: ["Kanye West"],
    mood: ["Workout", "Energetic"],
    year: 2007,
    album: "Graduation",
    duration: "5:12",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/PsO6ZnUZI0g/hqdefault.jpg",
    timeStamp: "6:30 AM",
    liked: true
  },
  {
    title: "Eye of the Tiger",
    singers: ["Survivor"],
    mood: ["Workout", "Motivational"],
    year: 1982,
    album: "Eye of the Tiger",
    duration: "4:05",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/btPJPFnesV4/hqdefault.jpg",
    timeStamp: "6:15 AM",
    liked: true
  },
  {
    title: "Hall of Fame",
    singers: ["The Script"],
    mood: ["Motivational", "Focus"],
    year: 2012,
    album: "Single",
    duration: "3:22",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/mk48xRzuNvA/hqdefault.jpg",
    timeStamp: "9:00 AM",
    liked: true
  },
  {
    title: "Stay",
    singers: ["The Kid LAROI", "Justin Bieber"],
    mood: ["Energetic"],
    year: 2021,
    album: "Single",
    duration: "2:21",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/kTJczUoc26U/hqdefault.jpg",
    timeStamp: "3:30 PM",
    liked: true
  },
  {
    title: "Thunder",
    singers: ["Imagine Dragons"],
    mood: ["Motivational", "Energetic"],
    year: 2017,
    album: "Evolve",
    duration: "3:07",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/fKopy74weus/hqdefault.jpg",
    timeStamp: "7:15 AM",
    liked: false
  },
  {
    title: "Run The World",
    singers: ["Beyoncé"],
    mood: ["Energetic", "Motivational"],
    year: 2011,
    album: "4",
    duration: "3:56",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/VBmMU_iwe6U/hqdefault.jpg",
    timeStamp: "7:30 AM",
    liked: false
  },

  // ───── ENGLISH – Party / Dance / Hype ─────
  {
    title: "Levitating",
    singers: ["Dua Lipa"],
    mood: ["Happy", "Dance"],
    year: 2020,
    album: "Future Nostalgia",
    duration: "3:23",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/TUVcZfQe-Kw/hqdefault.jpg",
    timeStamp: "4:45 PM",
    liked: false
  },
  {
    title: "Despacito",
    singers: ["Luis Fonsi", "Daddy Yankee"],
    mood: ["Party", "Feel Good"],
    year: 2017,
    album: "Vida",
    duration: "3:47",
    language: "Spanish",
    thumbnail: "https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg",
    timeStamp: "9:30 PM",
    liked: false
  },
  {
    title: "Industry Baby",
    singers: ["Lil Nas X"],
    mood: ["Hype"],
    year: 2021,
    album: "Montero",
    duration: "3:32",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/UTHLKHL_whs/hqdefault.jpg",
    timeStamp: "4:10 PM",
    liked: false
  },
  {
    title: "Let Me Love You",
    singers: ["DJ Snake", "Justin Bieber"],
    mood: ["Party"],
    year: 2016,
    album: "Encore",
    duration: "3:25",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/SMs0GnYze34/hqdefault.jpg",
    timeStamp: "10:00 PM",
    liked: false
  },
  {
    title: "Uptown Funk",
    singers: ["Bruno Mars"],
    mood: ["Party", "Dance"],
    year: 2014,
    album: "Uptown Special",
    duration: "4:30",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg",
    timeStamp: "5:00 PM",
    liked: false
  },
  {
    title: "Titanium",
    singers: ["David Guetta", "Sia"],
    mood: ["Dance", "Motivational"],
    year: 2011,
    album: "Nothing but the Beat",
    duration: "4:05",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/JRfuAukYTKg/hqdefault.jpg",
    timeStamp: "6:10 PM",
    liked: false
  },
  {
    title: "Cheap Thrills",
    singers: ["Sia"],
    mood: ["Party", "Dance", "Fun"],
    year: 2016,
    album: "This Is Acting",
    duration: "3:31",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/31crA53Dgu0/hqdefault.jpg",
    timeStamp: "9:10 PM",
    liked: false
  },
  {
    title: "Perfect Strangers",
    singers: ["Jonas Blue"],
    mood: ["Party"],
    year: 2016,
    album: "Blue",
    duration: "3:16",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/EkHTsc9PU2A/hqdefault.jpg",
    timeStamp: "9:50 PM",
    liked: false
  },
  {
    title: "Don't Start Now",
    singers: ["Dua Lipa"],
    mood: ["Party", "Dance"],
    year: 2019,
    album: "Future Nostalgia",
    duration: "3:27",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/oygrmJFKYZY/hqdefault.jpg",
    timeStamp: "10:20 PM",
    liked: false
  },
  {
    title: "Bad Guy",
    singers: ["Billie Eilish"],
    mood: ["Hype", "Cool"],
    year: 2019,
    album: "When We All Fall Asleep",
    duration: "3:14",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/DyDfgMOUjCI/hqdefault.jpg",
    timeStamp: "10:40 PM",
    liked: false
  },
  {
    title: "Shake It Off",
    singers: ["Taylor Swift"],
    mood: ["Happy", "Party", "Dance"],
    year: 2014,
    album: "1989",
    duration: "3:39",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/nfWlot6h_JM/hqdefault.jpg",
    timeStamp: "5:45 PM",
    liked: false
  },

  // ───── ENGLISH – Focus / Instrumental ─────
  {
    title: "Experience",
    singers: ["Ludovico Einaudi"],
    mood: ["Focus"],
    year: 2013,
    album: "In a Time Lapse",
    duration: "5:15",
    language: "Instrumental",
    thumbnail: "https://i.ytimg.com/vi/hN_q-_nGv4U/hqdefault.jpg",
    timeStamp: "9:30 AM",
    liked: false
  },
  {
    title: "Weightless",
    singers: ["Marconi Union"],
    mood: ["Focus", "Chill"],
    year: 2011,
    album: "Weightless",
    duration: "8:00",
    language: "Instrumental",
    thumbnail: "https://i.ytimg.com/vi/UfcAVejslrU/hqdefault.jpg",
    timeStamp: "10:00 AM",
    liked: false
  },
  {
    title: "Clair de Lune",
    singers: ["Claude Debussy"],
    mood: ["Focus", "Chill"],
    year: 1905,
    album: "Suite bergamasque",
    duration: "5:08",
    language: "Instrumental",
    thumbnail: "https://i.ytimg.com/vi/WNcsUNKlAKw/hqdefault.jpg",
    timeStamp: "10:30 AM",
    liked: false
  },
  {
    title: "Gymnopédie No.1",
    singers: ["Erik Satie"],
    mood: ["Focus", "Chill"],
    year: 1888,
    album: "Trois Gymnopédies",
    duration: "3:18",
    language: "Instrumental",
    thumbnail: "https://i.ytimg.com/vi/S-Xm7s9eGxU/hqdefault.jpg",
    timeStamp: "11:00 AM",
    liked: false
  },

  // ───── HINDI ─────
  {
    title: "Tum Hi Ho",
    singers: ["Arijit Singh"],
    mood: ["Sad", "Emotional"],
    year: 2013,
    album: "Aashiqui 2",
    duration: "4:22",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/Umqb9KENgmk/hqdefault.jpg",
    timeStamp: "12:15 AM",
    liked: false
  },
  {
    title: "Kesariya",
    singers: ["Arijit Singh"],
    mood: ["Romantic", "Warm"],
    year: 2022,
    album: "Brahmāstra",
    duration: "4:28",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/BddP6PYo2gs/hqdefault.jpg",
    timeStamp: "6:50 PM",
    liked: true
  },
  {
    title: "Kesariya (Lo-fi)",
    singers: ["Arijit Singh"],
    mood: ["Warm", "Chill"],
    year: 2022,
    album: "Brahmāstra",
    duration: "3:00",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/BddP6PYo2gs/hqdefault.jpg",
    timeStamp: "7:30 PM",
    liked: false
  },
  {
    title: "Apna Bana Le",
    singers: ["Arijit Singh"],
    mood: ["Soft", "Emotional"],
    year: 2022,
    album: "Bhediya",
    duration: "4:21",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/ElZfdU54Cp8/hqdefault.jpg",
    timeStamp: "11:05 PM",
    liked: true
  },
  {
    title: "Hawayein",
    singers: ["Arijit Singh"],
    mood: ["Romantic"],
    year: 2017,
    album: "Jab Harry Met Sejal",
    duration: "4:50",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/cYOB941gyXI/hqdefault.jpg",
    timeStamp: "7:10 PM",
    liked: false
  },
  {
    title: "Channa Mereya",
    singers: ["Arijit Singh"],
    mood: ["Sad"],
    year: 2016,
    album: "Ae Dil Hai Mushkil",
    duration: "4:49",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/284Ov7ysmfA/hqdefault.jpg",
    timeStamp: "1:10 AM",
    liked: false
  },
  {
    title: "Ghungroo",
    singers: ["Arijit Singh", "Shilpa Rao"],
    mood: ["Dance", "Happy"],
    year: 2019,
    album: "War",
    duration: "5:02",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/qFkNATtc3mc/hqdefault.jpg",
    timeStamp: "5:50 PM",
    liked: false
  },
  {
    title: "Nashe Si Chadh Gayi",
    singers: ["Arijit Singh"],
    mood: ["Party", "Dance", "Romantic"],
    year: 2016,
    album: "Befikre",
    duration: "3:57",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/Wd2B8OAotU8/hqdefault.jpg",
    timeStamp: "9:35 PM",
    liked: false
  },
  {
    title: "Shayad",
    singers: ["Arijit Singh"],
    mood: ["Warm", "Romantic"],
    year: 2020,
    album: "Love Aaj Kal",
    duration: "4:07",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/MJyKN-8UncM/hqdefault.jpg",
    timeStamp: "8:20 PM",
    liked: false
  },
  {
    title: "Ilahi",
    singers: ["Arijit Singh"],
    mood: ["Flow", "Feel Good"],
    year: 2013,
    album: "YJHD",
    duration: "3:32",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/fdubeMFwuGs/hqdefault.jpg",
    timeStamp: "4:35 PM",
    liked: false
  },
  {
    title: "Agar Tum Saath Ho",
    singers: ["Alka Yagnik", "Arijit Singh"],
    mood: ["Sad", "Warm"],
    year: 2015,
    album: "Tamasha",
    duration: "5:41",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/sK7riqg2mr4/hqdefault.jpg",
    timeStamp: "2:10 AM",
    liked: false
  },
  {
    title: "Tera Ban Jaunga",
    singers: ["Akhil Sachdeva", "Tulsi Kumar"],
    mood: ["Romantic", "Soft", "Emotional"],
    year: 2019,
    album: "Kabir Singh",
    duration: "3:56",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/Qdz5n1Xe5Qo/hqdefault.jpg",
    timeStamp: "8:15 PM",
    liked: false
  },
  {
    title: "Kaise Hua",
    singers: ["Vishal Mishra"],
    mood: ["Romantic", "Chill"],
    year: 2019,
    album: "Kabir Singh",
    duration: "3:54",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/WWXm39leYew/hqdefault.jpg",
    timeStamp: "8:05 PM",
    liked: false
  },
  {
    title: "Raataan Lambiyan",
    singers: ["Jubin Nautiyal", "Asees Kaur"],
    mood: ["Romantic", "Calm", "Soft"],
    year: 2021,
    album: "Shershaah",
    duration: "3:50",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/gvyUuxdRdR4/hqdefault.jpg",
    timeStamp: "7:35 PM",
    liked: true
  },
  {
    title: "Ranjha",
    singers: ["B Praak", "Jasleen Royal"],
    mood: ["Emotional", "Sad", "Romantic"],
    year: 2021,
    album: "Shershaah",
    duration: "3:48",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/VuG7ge_8I2Y/hqdefault.jpg",
    timeStamp: "11:30 PM",
    liked: false
  },
  {
    title: "Kar Gayi Chull",
    singers: ["Badshah", "Neha Kakkar"],
    mood: ["Party", "Dance", "Hype"],
    year: 2016,
    album: "Kapoor & Sons",
    duration: "3:07",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/NTHz9ephYTw/hqdefault.jpg",
    timeStamp: "9:20 PM",
    liked: true
  },
  {
    title: "Abhi Toh Party Shuru Hui Hai",
    singers: ["Badshah", "Aastha Gill"],
    mood: ["Party", "Hype", "Dance"],
    year: 2014,
    album: "Khoobsurat",
    duration: "2:59",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/8LZgzAZ2lpQ/hqdefault.jpg",
    timeStamp: "9:25 PM",
    liked: false
  },
  {
    title: "London Thumakda",
    singers: ["Neha Kakkar", "Sonu Kakkar"],
    mood: ["Wedding", "Dance", "Fun"],
    year: 2014,
    album: "Queen",
    duration: "3:50",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/udra3Mfw2oo/hqdefault.jpg",
    timeStamp: "9:45 PM",
    liked: false
  },
  {
    title: "Morni Banke",
    singers: ["Guru Randhawa", "Neha Kakkar"],
    mood: ["Dance", "Party", "Wedding"],
    year: 2018,
    album: "Badhaai Ho",
    duration: "3:18",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/1EadhOBcfI0/hqdefault.jpg",
    timeStamp: "9:55 PM",
    liked: false
  },
  {
    title: "Aankh Marey",
    singers: ["Neha Kakkar", "Mika Singh"],
    mood: ["Party", "Dance", "Hype"],
    year: 2018,
    album: "Simmba",
    duration: "3:32",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/_KhQT-LGb-4/hqdefault.jpg",
    timeStamp: "10:35 PM",
    liked: false
  },
  {
    title: "Malang",
    singers: ["Ved Sharma"],
    mood: ["Dance", "Feel Good"],
    year: 2020,
    album: "Malang",
    duration: "4:37",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/KBIq11mNB0I/hqdefault.jpg",
    timeStamp: "6:20 PM",
    liked: false
  },
  {
    title: "Kala Chashma",
    singers: ["Badshah", "Neha Kakkar"],
    mood: ["Party", "Dance"],
    year: 2016,
    album: "Baar Baar Dekho",
    duration: "3:07",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/k4yXQkG2s1E/hqdefault.jpg",
    timeStamp: "9:15 PM",
    liked: false
  },
  {
    title: "Bom Diggy Diggy",
    singers: ["Zack Knight", "Jasmin Walia"],
    mood: ["Party", "Dance", "Fun"],
    year: 2018,
    album: "Sonu Ke Titu Ki Sweety",
    duration: "3:58",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/yIIGQB6EMAM/hqdefault.jpg",
    timeStamp: "10:25 PM",
    liked: false
  },
  {
    title: "Dil Chori",
    singers: ["Yo Yo Honey Singh", "Simar Kaur"],
    mood: ["Party", "Dance", "Wedding"],
    year: 2018,
    album: "Sonu Ke Titu Ki Sweety",
    duration: "3:46",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/ZmDBbnmKpqQ/hqdefault.jpg",
    timeStamp: "10:45 PM",
    liked: false
  },
  {
    title: "Tujhe Kitna Chahne Lage",
    singers: ["Arijit Singh"],
    mood: ["Romantic", "Emotional"],
    year: 2019,
    album: "Kabir Singh",
    duration: "4:35",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/dGQWoHmfJ6Y/hqdefault.jpg",
    timeStamp: "8:00 PM",
    liked: false
  },
  {
    title: "Zindagi Kuch Toh Bata",
    singers: ["Jubin Nautiyal"],
    mood: ["Emotional", "Calm"],
    year: 2015,
    album: "Bajrangi Bhaijaan",
    duration: "5:10",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/8OUhLRLxv_g/hqdefault.jpg",
    timeStamp: "11:50 PM",
    liked: false
  },
  {
    title: "Dil Diyan Gallan",
    singers: ["Atif Aslam"],
    mood: ["Romantic", "Soft"],
    year: 2017,
    album: "Tiger Zinda Hai",
    duration: "4:18",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/eSx2NbqcmEA/mqdefault.jpg",
    timeStamp: "7:55 PM",
    liked: false
  },
  {
    title: "Woh Lamhe",
    singers: ["Atif Aslam"],
    mood: ["Sad", "Nostalgic"],
    year: 2006,
    album: "Zeher",
    duration: "4:55",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/j7S8TRf_D7A/hqdefault.jpg",
    timeStamp: "1:20 AM",
    liked: false
  },
  {
    title: "Ik Vaari Aa",
    singers: ["Arijit Singh"],
    mood: ["Emotional", "Sad"],
    year: 2016,
    album: "Raabta",
    duration: "5:26",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/WcmaKXOc5zo/hqdefault.jpg",
    timeStamp: "1:40 AM",
    liked: false
  },
  {
    title: "Mast Magan",
    singers: ["Arijit Singh"],
    mood: ["Romantic", "Happy"],
    year: 2014,
    album: "2 States",
    duration: "5:00",
    language: "Hindi",
    thumbnail: "https://i.ytimg.com/vi/6BHlF6jSeJY/hqdefault.jpg",
    timeStamp: "7:05 PM",
    liked: false
  },

  // ───── PUNJABI ─────
  {
    title: "We Rollin",
    singers: ["Shubh"],
    mood: ["Hype", "Cool", "Chill"],
    year: 2021,
    album: "Single",
    duration: "3:19",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/Ml9uJNF_kXk/hqdefault.jpg",
    timeStamp: "3:40 PM",
    liked: false
  },
  {
    title: "295",
    singers: ["Sidhu Moose Wala"],
    mood: ["Serious", "Real Talk", "Emotional"],
    year: 2021,
    album: "Moosetape",
    duration: "4:10",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/n_FCrCQ6-bA/hqdefault.jpg",
    timeStamp: "4:20 PM",
    liked: false
  },
  {
    title: "Proper Patola",
    singers: ["Diljit Dosanjh", "Badshah"],
    mood: ["Party", "Cool", "Dance"],
    year: 2018,
    album: "Namaste England",
    duration: "3:05",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/YmXJp4RtBCM/hqdefault.jpg",
    timeStamp: "10:05 PM",
    liked: false
  },
  {
    title: "High Heels",
    singers: ["Yo Yo Honey Singh", "Jaz Dhami"],
    mood: ["Party", "Dance", "Hype"],
    year: 2016,
    album: "Ki & Ka",
    duration: "3:24",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/N_KpjLhJa1k/hqdefault.jpg",
    timeStamp: "10:15 PM",
    liked: true
  },
  {
    title: "G.O.A.T",
    singers: ["Diljit Dosanjh"],
    mood: ["Hype", "Cool"],
    year: 2020,
    album: "G.O.A.T",
    duration: "3:09",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/7SBMnqS0bZQ/hqdefault.jpg",
    timeStamp: "4:00 PM",
    liked: false
  },
  {
    title: "Lover",
    singers: ["Diljit Dosanjh"],
    mood: ["Romantic", "Chill"],
    year: 2021,
    album: "MoonChild Era",
    duration: "3:22",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/O9FItjkIjFI/hqdefault.jpg",
    timeStamp: "7:25 PM",
    liked: false
  },
  {
    title: "Excuses",
    singers: ["AP Dhillon", "Gurinder Gill"],
    mood: ["Chill", "Romantic"],
    year: 2020,
    album: "Single",
    duration: "3:24",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/cqpENPfcsBs/hqdefault.jpg",
    timeStamp: "7:50 PM",
    liked: true
  },
  {
    title: "Brown Munde",
    singers: ["AP Dhillon", "Gurinder Gill", "Shinda Kahlon"],
    mood: ["Hype", "Cool", "Party"],
    year: 2020,
    album: "Single",
    duration: "3:44",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/gNBbOXKSjb8/hqdefault.jpg",
    timeStamp: "10:50 PM",
    liked: false
  },
  {
    title: "Ikk Kudi",
    singers: ["Diljit Dosanjh"],
    mood: ["Emotional", "Nostalgic"],
    year: 2016,
    album: "Udta Punjab",
    duration: "4:00",
    language: "Punjabi",
    thumbnail: "https://i.ytimg.com/vi/qb-aMz4T4Qg/hqdefault.jpg",
    timeStamp: "2:30 AM",
    liked: false
  },

  // ───── TELUGU / TAMIL ─────
  {
    title: "Naatu Naatu",
    singers: ["Rahul Sipligunj", "Kaala Bhairava"],
    mood: ["Dance", "Energetic"],
    year: 2022,
    album: "RRR",
    duration: "3:34",
    language: "Telugu",
    thumbnail: "https://i.ytimg.com/vi/OsU0CGZoV8E/hqdefault.jpg",
    timeStamp: "5:30 PM",
    liked: false
  },
  {
    title: "Kannazhaga",
    singers: ["Sid Sriram"],
    mood: ["Romantic", "Emotional"],
    year: 2019,
    album: "Kolamaavu Kokila",
    duration: "4:12",
    language: "Tamil",
    thumbnail: "https://i.ytimg.com/vi/1y_3HfCGPvw/hqdefault.jpg",
    timeStamp: "8:30 PM",
    liked: false
  },
  {
    title: "Rowdy Baby",
    singers: ["Dhanush", "Dhee"],
    mood: ["Dance", "Party"],
    year: 2018,
    album: "Maari 2",
    duration: "4:15",
    language: "Tamil",
    thumbnail: "https://i.ytimg.com/vi/EuNGNODH1IM/hqdefault.jpg",
    timeStamp: "5:15 PM",
    liked: false
  },
  {
    title: "Butta Bomma",
    singers: ["Armaan Malik"],
    mood: ["Romantic", "Happy"],
    year: 2019,
    album: "Ala Vaikunthapurramuloo",
    duration: "3:35",
    language: "Telugu",
    thumbnail: "https://i.ytimg.com/vi/OHWoNT-JFlA/hqdefault.jpg",
    timeStamp: "7:40 PM",
    liked: false
  },

  // ───── KOREAN (K-Pop) ─────
  {
    title: "Gangnam Style",
    singers: ["PSY"],
    mood: ["Fun", "Dance", "Party"],
    year: 2012,
    album: "PSY 6",
    duration: "3:39",
    language: "Korean",
    thumbnail: "https://i.ytimg.com/vi/9bZkp7q19f0/hqdefault.jpg",
    timeStamp: "5:20 PM",
    liked: false
  },
  {
    title: "How You Like That",
    singers: ["BLACKPINK"],
    mood: ["Hype", "Powerful", "Energetic"],
    year: 2020,
    album: "The Album",
    duration: "3:01",
    language: "Korean",
    thumbnail: "https://i.ytimg.com/vi/ioNng23DkIM/hqdefault.jpg",
    timeStamp: "5:35 PM",
    liked: false
  },
  {
    title: "Dynamite",
    singers: ["BTS"],
    mood: ["Happy", "Dance", "Feel Good"],
    year: 2020,
    album: "Single",
    duration: "3:19",
    language: "Korean",
    thumbnail: "https://i.ytimg.com/vi/gdZLi9oWNZg/hqdefault.jpg",
    timeStamp: "4:55 PM",
    liked: false
  },
  {
    title: "Butter",
    singers: ["BTS"],
    mood: ["Happy", "Party"],
    year: 2021,
    album: "Single",
    duration: "2:45",
    language: "Korean",
    thumbnail: "https://i.ytimg.com/vi/WMweEpGlu_U/hqdefault.jpg",
    timeStamp: "5:05 PM",
    liked: false
  },
  {
    title: "Kill This Love",
    singers: ["BLACKPINK"],
    mood: ["Hype", "Powerful"],
    year: 2019,
    album: "Kill This Love",
    duration: "2:50",
    language: "Korean",
    thumbnail: "https://i.ytimg.com/vi/2S24-y0Ij3Y/hqdefault.jpg",
    timeStamp: "5:40 PM",
    liked: false
  },

  // ───── SPANISH ─────
  {
    title: "La Bamba",
    singers: ["Ritchie Valens"],
    mood: ["Feel Good", "Dance"],
    year: 1958,
    album: "Ritchie Valens",
    duration: "2:08",
    language: "Spanish",
    thumbnail: "https://i.ytimg.com/vi/XFWYvC-Lp4M/hqdefault.jpg",
    timeStamp: "2:45 PM",
    liked: false
  },
  {
    title: "Con Calma",
    singers: ["Daddy Yankee"],
    mood: ["Party", "Dance"],
    year: 2019,
    album: "Single",
    duration: "3:15",
    language: "Spanish",
    thumbnail: "https://i.ytimg.com/vi/NkNkXe1kFu0/hqdefault.jpg",
    timeStamp: "9:55 PM",
    liked: false
  },
  {
    title: "Taki Taki",
    singers: ["DJ Snake", "Selena Gomez", "Cardi B"],
    mood: ["Party", "Hype"],
    year: 2018,
    album: "Single",
    duration: "3:33",
    language: "Spanish",
    thumbnail: "https://i.ytimg.com/vi/ixiak72ZG-o/hqdefault.jpg",
    timeStamp: "10:55 PM",
    liked: false
  },

  // ───── FRENCH ─────
  {
    title: "Alors On Danse",
    singers: ["Stromae"],
    mood: ["Dance", "Chill"],
    year: 2009,
    album: "Cheese",
    duration: "3:55",
    language: "French",
    thumbnail: "https://i.ytimg.com/vi/oiKj0Z_Xnjc/hqdefault.jpg",
    timeStamp: "11:10 PM",
    liked: false
  },
  {
    title: "Papaoutai",
    singers: ["Stromae"],
    mood: ["Emotional", "Dance"],
    year: 2013,
    album: "Racine Carrée",
    duration: "4:12",
    language: "French",
    thumbnail: "https://i.ytimg.com/vi/oiKj0Z_Xnjc/hqdefault.jpg",
    timeStamp: "11:15 PM",
    liked: false
  },

  // ───── ARABIC ─────
  {
    title: "Hayati",
    singers: ["Elissa"],
    mood: ["Romantic", "Emotional"],
    year: 2018,
    album: "Elli Beny W Bynak",
    duration: "4:05",
    language: "Arabic",
    thumbnail: "https://i.ytimg.com/vi/qBMm0EnY2cI/hqdefault.jpg",
    timeStamp: "8:35 PM",
    liked: false
  },

  // ───── AFROBEATS ─────
  {
    title: "Love Nwantiti",
    singers: ["CKay"],
    mood: ["Chill", "Romantic", "Feel Good"],
    year: 2019,
    album: "Single",
    duration: "2:07",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/U780ZkegUL4/hqdefault.jpg",
    timeStamp: "6:40 PM",
    liked: false
  },
  {
    title: "Essence",
    singers: ["Wizkid", "Tems"],
    mood: ["Chill", "Romantic"],
    year: 2020,
    album: "Made in Lagos",
    duration: "4:04",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/GEoIRUUU0uA/hqdefault.jpg",
    timeStamp: "6:55 PM",
    liked: false
  },

  // ───── MORE ENGLISH – Various moods ─────
  {
    title: "Yellow",
    singers: ["Coldplay"],
    mood: ["Emotional", "Warm"],
    year: 2000,
    album: "Parachutes",
    duration: "4:29",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/yKNxeF4KMsY/hqdefault.jpg",
    timeStamp: "5:55 PM",
    liked: false
  },
  {
    title: "The Scientist",
    singers: ["Coldplay"],
    mood: ["Sad", "Emotional"],
    year: 2002,
    album: "A Rush of Blood to the Head",
    duration: "5:09",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/RB-RcX5DS5A/hqdefault.jpg",
    timeStamp: "2:50 AM",
    liked: false
  },
  {
    title: "Clocks",
    singers: ["Coldplay"],
    mood: ["Focus", "Energetic"],
    year: 2002,
    album: "A Rush of Blood to the Head",
    duration: "5:07",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/d020hcWA_Wg/hqdefault.jpg",
    timeStamp: "11:30 AM",
    liked: false
  },
  {
    title: "Photograph",
    singers: ["Ed Sheeran"],
    mood: ["Emotional", "Warm"],
    year: 2014,
    album: "X",
    duration: "4:19",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/nSDgHBxUbVQ/hqdefault.jpg",
    timeStamp: "5:00 AM",
    liked: false
  },
  {
    title: "Bohemian Rhapsody",
    singers: ["Queen"],
    mood: ["Energetic", "Emotional"],
    year: 1975,
    album: "A Night at the Opera",
    duration: "5:54",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg",
    timeStamp: "8:45 PM",
    liked: false
  },
  {
    title: "Hotel California",
    singers: ["Eagles"],
    mood: ["Chill", "Night Drive"],
    year: 1977,
    album: "Hotel California",
    duration: "6:30",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/EqPtz5qN7HM/hqdefault.jpg",
    timeStamp: "12:00 AM",
    liked: false
  },
  {
    title: "Africa",
    singers: ["Toto"],
    mood: ["Feel Good", "Chill"],
    year: 1982,
    album: "Toto IV",
    duration: "4:55",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/FTQbiNvZqaY/hqdefault.jpg",
    timeStamp: "1:00 PM",
    liked: false
  },
  {
    title: "Mr. Brightside",
    singers: ["The Killers"],
    mood: ["Energetic", "Emotional"],
    year: 2003,
    album: "Hot Fuss",
    duration: "3:43",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/gGdGFtwCNBE/hqdefault.jpg",
    timeStamp: "11:40 PM",
    liked: false
  },
  {
    title: "Viva La Vida",
    singers: ["Coldplay"],
    mood: ["Motivational", "Feel Good"],
    year: 2008,
    album: "Viva la Vida",
    duration: "4:01",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/dvgZkm1xWPE/hqdefault.jpg",
    timeStamp: "12:00 PM",
    liked: true
  },
  {
    title: "Demons",
    singers: ["Imagine Dragons"],
    mood: ["Emotional", "Sad"],
    year: 2012,
    album: "Night Visions",
    duration: "2:57",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/mWRsgZuwf_8/hqdefault.jpg",
    timeStamp: "1:00 AM",
    liked: false
  },
  {
    title: "Radioactive",
    singers: ["Imagine Dragons"],
    mood: ["Energetic", "Motivational"],
    year: 2012,
    album: "Night Visions",
    duration: "3:06",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/ktvTqknDobU/hqdefault.jpg",
    timeStamp: "7:45 AM",
    liked: false
  },
  {
    title: "Circles",
    singers: ["Post Malone"],
    mood: ["Chill", "Sad"],
    year: 2019,
    album: "Hollywood's Bleeding",
    duration: "3:35",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/wXhTHyIgQ_U/hqdefault.jpg",
    timeStamp: "11:55 PM",
    liked: false
  },
  {
    title: "Golden Hour",
    singers: ["JVKE"],
    mood: ["Romantic", "Warm", "Happy"],
    year: 2022,
    album: "this is what ____ feels like",
    duration: "3:29",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/PEM0kU97R9s/hqdefault.jpg",
    timeStamp: "6:00 PM",
    liked: true
  },
  {
    title: "Cruel Summer",
    singers: ["Taylor Swift"],
    mood: ["Energetic", "Feel Good"],
    year: 2019,
    album: "Lover",
    duration: "2:58",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/ic8j13piAhQ/hqdefault.jpg",
    timeStamp: "3:15 PM",
    liked: false
  },
  {
    title: "Anti-Hero",
    singers: ["Taylor Swift"],
    mood: ["Chill", "Mood"],
    year: 2022,
    album: "Midnights",
    duration: "3:20",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/b1kbLwvqugk/hqdefault.jpg",
    timeStamp: "10:10 PM",
    liked: false
  },
  {
    title: "I'm Yours",
    singers: ["Jason Mraz"],
    mood: ["Happy", "Warm", "Chill"],
    year: 2008,
    album: "We Sing. We Dance. We Steal Things.",
    duration: "4:02",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/EkHTsc9PU2A/hqdefault.jpg",
    timeStamp: "2:00 PM",
    liked: false
  },
  {
    title: "Wonderwall",
    singers: ["Oasis"],
    mood: ["Chill", "Nostalgic"],
    year: 1995,
    album: "(What's the Story) Morning Glory?",
    duration: "4:18",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/bx1Bh8ZvH84/hqdefault.jpg",
    timeStamp: "3:45 PM",
    liked: false
  },
  {
    title: "Stand By Me",
    singers: ["Ben E. King"],
    mood: ["Warm", "Feel Good", "Nostalgic"],
    year: 1961,
    album: "Don't Play That Song!",
    duration: "2:57",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/hwZNL7QVJjE/hqdefault.jpg",
    timeStamp: "1:30 PM",
    liked: false
  },
  {
    title: "We Will Rock You",
    singers: ["Queen"],
    mood: ["Energetic", "Hype", "Workout"],
    year: 1977,
    album: "News of the World",
    duration: "2:02",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/-tJYN-eG1zk/hqdefault.jpg",
    timeStamp: "6:50 AM",
    liked: false
  },
  {
    title: "Stairway to Heaven",
    singers: ["Led Zeppelin"],
    mood: ["Focus", "Emotional"],
    year: 1971,
    album: "Led Zeppelin IV",
    duration: "8:02",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/QkF3oxziUI4/hqdefault.jpg",
    timeStamp: "10:50 AM",
    liked: false
  },
  {
    title: "Smells Like Teen Spirit",
    singers: ["Nirvana"],
    mood: ["Energetic"],
    year: 1991,
    album: "Nevermind",
    duration: "5:01",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/hTWKbfoikeg/hqdefault.jpg",
    timeStamp: "4:30 PM",
    liked: false
  },
  {
    title: "Numb",
    singers: ["Linkin Park"],
    mood: ["Energetic", "Emotional"],
    year: 2003,
    album: "Meteora",
    duration: "3:05",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/kXYiU_JCYtU/hqdefault.jpg",
    timeStamp: "4:40 PM",
    liked: false
  },
  {
    title: "In The End",
    singers: ["Linkin Park"],
    mood: ["Emotional", "Energetic"],
    year: 2000,
    album: "Hybrid Theory",
    duration: "3:36",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/eVTXPUF4Oz4/hqdefault.jpg",
    timeStamp: "4:45 PM",
    liked: false
  },
  {
    title: "Lose Yourself",
    singers: ["Eminem"],
    mood: ["Motivational", "Workout"],
    year: 2002,
    album: "8 Mile OST",
    duration: "5:26",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/xFYQQPAOz7Y/hqdefault.jpg",
    timeStamp: "6:05 AM",
    liked: false
  },
  {
    title: "God's Plan",
    singers: ["Drake"],
    mood: ["Chill", "Feel Good"],
    year: 2018,
    album: "Scorpion",
    duration: "3:19",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/xpVfcZ0ZcFM/hqdefault.jpg",
    timeStamp: "3:20 PM",
    liked: false
  },
  {
    title: "One Dance",
    singers: ["Drake"],
    mood: ["Chill", "Party"],
    year: 2016,
    album: "Views",
    duration: "2:53",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/iHNovZUZM3A/hqdefault.jpg",
    timeStamp: "9:05 PM",
    liked: false
  },
  {
    title: "Blueberry Faygo",
    singers: ["Lil Mosey"],
    mood: ["Chill", "Flow"],
    year: 2019,
    album: "Certified Hitmaker",
    duration: "2:39",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/UGWFcK3ooR0/hqdefault.jpg",
    timeStamp: "2:35 PM",
    liked: false
  },
  {
    title: "Rockstar",
    singers: ["Post Malone", "21 Savage"],
    mood: ["Chill", "Hype"],
    year: 2017,
    album: "beerbongs & bentleys",
    duration: "3:39",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/UceaB4D0jpo/hqdefault.jpg",
    timeStamp: "11:00 PM",
    liked: false
  },
  {
    title: "Flowers",
    singers: ["Miley Cyrus"],
    mood: ["Happy", "Empowering"],
    year: 2023,
    album: "Endless Summer Vacation",
    duration: "3:21",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/G7KNmW9a75Y/hqdefault.jpg",
    timeStamp: "12:30 PM",
    liked: false
  },
  {
    title: "As Long As You Love Me",
    singers: ["Justin Bieber"],
    mood: ["Romantic", "Feel Good"],
    year: 2012,
    album: "Believe",
    duration: "3:31",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/EBazCNO7TSk/hqdefault.jpg",
    timeStamp: "2:00 AM",
    liked: false
  },
  {
    title: "Eastside",
    singers: ["Benny Blanco", "Halsey", "Khalid"],
    mood: ["Chill", "Romantic"],
    year: 2018,
    album: "Single",
    duration: "3:14",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/H-MqgbKhdem/hqdefault.jpg",
    timeStamp: "8:00 AM",
    liked: false
  },
  {
    title: "Location",
    singers: ["Khalid"],
    mood: ["Chill", "Warm"],
    year: 2016,
    album: "American Teen",
    duration: "3:43",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/h4YBGZULKMs/hqdefault.jpg",
    timeStamp: "8:30 AM",
    liked: false
  },
  {
    title: "Best Part",
    singers: ["Daniel Caesar", "H.E.R."],
    mood: ["Romantic", "Chill"],
    year: 2017,
    album: "Freudian",
    duration: "3:29",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/7O8qlP4OfFE/hqdefault.jpg",
    timeStamp: "9:10 AM",
    liked: false
  },
  {
    title: "Something Just Like This",
    singers: ["The Chainsmokers", "Coldplay"],
    mood: ["Feel Good", "Chill"],
    year: 2017,
    album: "Memories...Do Not Open",
    duration: "4:07",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/FM7MFYoylVs/hqdefault.jpg",
    timeStamp: "10:05 AM",
    liked: false
  },
  {
    title: "Slow Dancing in the Dark",
    singers: ["Joji"],
    mood: ["Sad", "Chill", "Night Drive"],
    year: 2018,
    album: "BALLADS 1",
    duration: "3:19",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/mS1_YoKTG0I/hqdefault.jpg",
    timeStamp: "12:35 AM",
    liked: false
  },
  {
    title: "Glimpse of Us",
    singers: ["Joji"],
    mood: ["Sad", "Emotional"],
    year: 2022,
    album: "Smithereens",
    duration: "3:43",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/hTSmCDKhfFg/hqdefault.jpg",
    timeStamp: "1:50 AM",
    liked: false
  },
  {
    title: "Sweater Weather",
    singers: ["The Neighbourhood"],
    mood: ["Chill", "Night Drive"],
    year: 2012,
    album: "I Love You.",
    duration: "4:00",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/GCypEPAngmA/hqdefault.jpg",
    timeStamp: "11:25 PM",
    liked: true
  },
  {
    title: "Stressed Out",
    singers: ["Twenty One Pilots"],
    mood: ["Chill", "Emotional"],
    year: 2015,
    album: "Blurryface",
    duration: "3:22",
    language: "English",
    thumbnail: "https://i.ytimg.com/vi/pXRviuL6vMY/hqdefault.jpg",
    timeStamp: "11:35 PM",
    liked: false
  }
];

const songPoolSlice = createSlice({
    name : "songPool",
    initialState : {value : songs},
    reducers : {
        toggleLike: (state, action) => {
          const index = state.value.findIndex(s => s.title === action.payload.title);
          if (index !== -1) {
              state.value[index].liked = !state.value[index].liked;
          }},
        addSong : (state,action) => {
          state.value = [...state.value,action.payload];
          }
      }
});

export const {toggleLike,addSong} = songPoolSlice.actions;
export default songPoolSlice.reducer;